/* @flow */

export default (moduleName: string, version: string, options: $Shape<{ flowPragma: boolean }>) => {
  if (options.flowPragma) {
    return "// @flow\n\n"
  }

  return `/**
  * Flowtype definitions for ${moduleName}
  * Generated by Flowgen from a Typescript Definition
  * Flowgen v${version}
  * Author: [Joar Wilk](http://twitter.com/joarwilk)
  * Repo: http://github.com/joarwilk/flowgen
  */

  `;
}
